import type { Metadata } from "next";
import Image from "next/image";
import { League_Spartan, Antonio } from "next/font/google";
import "./globals.css";
import NavLink from "./NavLink";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});

const antonio = Antonio({
  subsets: ["latin"],
  variable: "--font-antonio",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} font-sans min-h-full bg-planetGray-900 text-white container mx-auto`}
      >
        <Image
          className="absolute inset-0 z-0 w-full h-full object-cover pointer-events-none"
          src="/assets/background-stars.svg"
          alt="Background Image with Stars"
          width={1920}
          height={1080}
        />
        <nav className="flex flex-row justify-between items-center px-8 py-7">
          <span className="font-mono font-semibold uppercase text-3xl ">
            The Planets
          </span>
          <ul className="flex flex-row gap-8 ">
            <NavLink>mercury</NavLink>
            <NavLink>venus</NavLink>
            <NavLink>earth</NavLink>
            <NavLink>mars</NavLink>
            <NavLink>jupiter</NavLink>
            <NavLink>saturn</NavLink>
            <NavLink>uranus</NavLink>
            <NavLink>neptune</NavLink>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
